### PR TITLE
Add SSO tokens document

### PR DESCRIPTION
**Pull request by SuzukiShintaro**
Add document of /api/v1/sso_tokens

### CODE REVIEW

**Comment by nkuroda** [comment]
:+1:

**Comment by ppworks** [comment]
寿司ゆき:ok

**Comment by takuyan** [comment]
:+1:

**Comment by khirayama** [comment]
😎

**Comment by ppworks** [comment]
Have this feature already been implemented?

**Comment by makiton** [comment]
Yes, but now testing with our client.
It's scheduled on later in Oct. If we finished that then I'll merge by myself.

**Comment by ppworks** [comment]
> I'll merge by myself.

寿司ゆき:ok

**Comment by makiton** [comment]
It's released. I merge this.

**Comment by takuyan** [comment]
+1

**Comment by ppworks** [comment]
:+1:

**Pull request merged**
